#ifndef ___MODEL_MODEL_ORT_H
#define ___MODEL_MODEL_ORT_H
/* Auto-generated by bin2c.py */
#include <stddef.h>

/* Правка v2m (вручную; генератора bin2c.py в репозитории нет, файл не
   перегенерируется): символы определены в C-файле model.ort.c и имеют
   C-сцепление, поэтому объявления обёрнуты в extern "C". Без обёртки MSVC
   мангляет имена глобальных переменных в C++ (?model_ort_start@@3QBEB) и
   линковка libv2m падает с LNK2019 на ort_inference.cpp:91; в Itanium ABI
   (Linux, Android) имена глобальных переменных не манглятся, поэтому там
   сборка проходит и без обёртки. */
#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char model_ort_start[];
extern const size_t model_ort_size;

#ifdef __cplusplus
}
#endif

#endif
