name: Build Desktop Distributives

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make scripts executable (Linux)
      if: runner.os == 'Linux'
      working-directory: app
      run: chmod +x ./gradlew

    - name: Build for Linux
      if: runner.os == 'Linux'
      working-directory: app
      run: ./gradlew :desktopApp:packageDistributionForCurrentOS

    - name: Build for Windows
      if: runner.os == 'Windows'
      working-directory: app
      run: .\gradlew.bat :desktopApp:packageDistributionForCurrentOS

    # Загрузка Linux-дистрибутива из точной папки, которую вы указали
    - name: Upload Linux Artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: v2m-linux-x64-distributive
        # Символ * подставит любую версию (например, 1.0.0 или 1.0.1)
        path: dist/out/v2m-linux-x64-*/
        if-no-files-found: error

    # Загрузка Windows-дистрибутива из аналогичной папки
    - name: Upload Windows Artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: v2m-windows-x64-distributive
        path: dist/out/v2m-windows-x64-*/
        if-no-files-found: error
